os: remove specs for ruby bundled gems debug, racc and rbs
This is to get rid of warning messages on every ruby invocation:

```
Ignoring debug-1.9.2 because its extensions are not built. Try: gem pristine debug --version 1.9.2
Ignoring racc-1.7.3 because its extensions are not built. Try: gem pristine racc --version 1.7.3
Ignoring rbs-3.4.0 because its extensions are not built. Try: gem pristine rbs --version 3.4.0
```

Ruby build prints these messages:

```
*** Following extensions are not compiled:
debug-1.9.2/ext/debug:
        Could not be configured. It will not be installed.
        /build/ruby-3.3.8/lib/rubygems/platform.rb:18: undefined method `target_rbconfig' for module Gem
        Check .bundle/gems/debug-1.9.2/ext/debug/mkmf.log for more details.
racc-1.7.3/ext/racc/cparse:
        Could not be configured. It will not be installed.
        /build/ruby-3.3.8/lib/rubygems/platform.rb:18: undefined method `target_rbconfig' for module Gem
        Check .bundle/gems/racc-1.7.3/ext/racc/cparse/mkmf.log for more details.
rbs-3.4.0/ext/rbs_extension:
        Could not be configured. It will not be installed.
        /build/ruby-3.3.8/lib/rubygems/platform.rb:18: undefined method `target_rbconfig' for module Gem
        Check .bundle/gems/rbs-3.4.0/ext/rbs_extension/mkmf.log for more details.
*** Fix the problems, then remove these directories and try again if you want.
```

mkmf.log contains:

```
extconf.h is:
/* begin */
1: #ifndef EXTCONF_H
2: #define EXTCONF_H
3: #define HAVE_RB_ISEQ 1
4: #define HAVE_RB_ISEQ_PARAMETERS 1
5: #define HAVE_RB_ISEQ_CODE_LOCATION 1
6: #define HAVE_RB_ISEQ_TYPE 1
7: #endif
/* end */

/build/ruby-3.3.8/lib/rubygems/platform.rb:18: undefined method `target_rbconfig' for module Gem
        /build/ruby-3.3.8/lib/rubygems/platform.rb:18:in `local'
        ./ext/extmk.rb:581:in `block in create_makefile'
        /build/ruby-3.3.8/lib/mkmf.rb:2402:in `create_makefile'
        ./ext/extmk.rb:140:in `create_makefile'
        ./ext/extmk.rb:563:in `create_makefile'
        /build/ruby-3.3.8/.bundle/gems/debug-1.9.2/ext/debug/extconf.rb:27:in `<top (required)>'
        ./ext/extmk.rb:225:in `load'
        ./ext/extmk.rb:225:in `block in extmake'
        /build/ruby-3.3.8/lib/mkmf.rb:314:in `open'
        ./ext/extmk.rb:221:in `extmake'
        ./ext/extmk.rb:648:in `block in <main>'
        ./ext/extmk.rb:644:in `each'
        ./ext/extmk.rb:644:in `<main>'
```